/**
 * Celebration banner copy + palette for each seasonal theme.
 *
 * Data only (no React) so the mapping is trivially testable and every theme is
 * covered by construction: the type keys onto `SeasonalThemeId`, and
 * `THEME_BANNERS` is a `Record<HolidayThemeId, ...>` so a new holiday without a
 * banner is a compile error.
 *
 * `short` is the compact label reused by the banner and by anything that needs a
 * one-word celebration name; `subtitle` is the friendly second line.
 */
import type { SeasonalThemeId } from './holidayCalendar';

/** Every concrete theme (everything except 'none'). */
export type HolidayThemeId = Exclude<SeasonalThemeId, 'none'>;

export interface ThemeBanner {
  /** Short celebration label, e.g. "Christmas". */
  short: string;
  /** Headline greeting, e.g. "Merry Christmas!". */
  greeting: string;
  /** Friendly supporting line shown under the greeting. */
  subtitle: string;
  /** Emoji used as the banner glyph. */
  emoji: string;
  /** Tailwind gradient + border + text classes for the banner shell. */
  gradient: string;
  border: string;
  text: string;
  /** Accent colour for the small "goes live" pill and progress fill. */
  accent: string;
  /** Confetti colours used when the banner is tapped. */
  confetti: string[];
}

/** One banner per concrete theme — exhaustive by type. */
export const THEME_BANNERS: Record<HolidayThemeId, ThemeBanner> = {
  halloween: {
    short: 'Halloween',
    greeting: 'Happy Halloween!',
    subtitle: 'Spooky season savings and treats all week long.',
    emoji: '🎃',
    gradient: 'from-orange-600 via-amber-500 to-purple-700',
    border: 'border-orange-400/50',
    text: 'text-white',
    accent: '#fb923c',
    confetti: ['#f97316', '#a855f7', '#22c55e', '#eab308'],
  },
  christmas: {
    short: 'Christmas',
    greeting: 'Merry Christmas!',
    subtitle: 'Ho, ho, ho — festive offers and a merry ride for all.',
    emoji: '🎄',
    gradient: 'from-red-700 via-red-500 to-emerald-600',
    border: 'border-red-400/50',
    text: 'text-white',
    accent: '#dc2626',
    confetti: ['#dc2626', '#16a34a', '#ffffff', '#facc15'],
  },
  stpatricks: {
    short: "St. Patrick's Day",
    greeting: "Happy St. Patrick's Day!",
    subtitle: 'Top of the morning — a bit of luck on every mile.',
    emoji: '🍀',
    gradient: 'from-emerald-700 via-green-500 to-emerald-400',
    border: 'border-emerald-300/50',
    text: 'text-white',
    accent: '#22c55e',
    confetti: ['#22c55e', '#15803d', '#ffffff', '#facc15'],
  },
  newyear: {
    short: "New Year's Eve",
    greeting: 'Happy New Year!',
    subtitle: "Here's to a bright new year of great rides.",
    emoji: '🎆',
    gradient: 'from-indigo-700 via-violet-600 to-fuchsia-600',
    border: 'border-violet-300/50',
    text: 'text-white',
    accent: '#8b5cf6',
    confetti: ['#8b5cf6', '#f59e0b', '#22d3ee', '#ffffff'],
  },
  valentines: {
    short: "Valentine's Day",
    greeting: "Happy Valentine's Day!",
    subtitle: 'Share the love — the perfect gift for the one who rides.',
    emoji: '❤️',
    gradient: 'from-rose-700 via-pink-500 to-rose-400',
    border: 'border-rose-300/50',
    text: 'text-white',
    accent: '#f43f5e',
    confetti: ['#f43f5e', '#ec4899', '#ffffff', '#fda4af'],
  },
  easter: {
    short: 'Easter',
    greeting: 'Happy Easter!',
    subtitle: 'Hop into spring with eggs-tra special deals.',
    emoji: '🐣',
    gradient: 'from-pink-400 via-sky-300 to-yellow-300',
    border: 'border-pink-300/50',
    text: 'text-white',
    accent: '#38bdf8',
    confetti: ['#f472b6', '#38bdf8', '#facc15', '#a7f3d0'],
  },
  thanksgiving: {
    short: 'Thanksgiving',
    greeting: 'Happy Thanksgiving!',
    subtitle: 'Grateful for every customer — feast on these deals.',
    emoji: '🦃',
    gradient: 'from-amber-700 via-orange-500 to-amber-400',
    border: 'border-amber-300/50',
    text: 'text-white',
    accent: '#f59e0b',
    confetti: ['#f59e0b', '#b45309', '#dc2626', '#fde68a'],
  },
  cny: {
    short: 'Chinese New Year',
    greeting: 'Happy Chinese New Year!',
    subtitle: 'Wishing you prosperity and joy for the year ahead.',
    emoji: '🏮',
    gradient: 'from-red-700 via-red-500 to-amber-400',
    border: 'border-red-300/50',
    text: 'text-white',
    accent: '#ef4444',
    confetti: ['#ef4444', '#f59e0b', '#facc15', '#ffffff'],
  },
  midautumn: {
    short: 'Mid-Autumn Festival',
    greeting: 'Happy Mid-Autumn Festival!',
    subtitle: 'Mooncakes, lanterns and a brilliant ride under the full moon.',
    emoji: '🥮',
    gradient: 'from-amber-600 via-yellow-500 to-indigo-500',
    border: 'border-amber-300/50',
    text: 'text-white',
    accent: '#eab308',
    confetti: ['#eab308', '#f59e0b', '#a855f7', '#ffffff'],
  },
  diwali: {
    short: 'Diwali',
    greeting: 'Happy Diwali!',
    subtitle: 'Wishing you a festival of lights full of joy and safety.',
    emoji: '🪔',
    gradient: 'from-fuchsia-700 via-orange-500 to-amber-400',
    border: 'border-fuchsia-300/50',
    text: 'text-white',
    accent: '#d946ef',
    confetti: ['#d946ef', '#f97316', '#facc15', '#ffffff'],
  },
  holi: {
    short: 'Holi',
    greeting: 'Happy Holi!',
    subtitle: 'May your days be as colourful as the festival of spring.',
    emoji: '🎨',
    gradient: 'from-fuchsia-500 via-yellow-400 to-cyan-400',
    border: 'border-yellow-300/50',
    text: 'text-white',
    accent: '#ec4899',
    confetti: ['#ec4899', '#facc15', '#22d3ee', '#a3e635'],
  },
  eidfitr: {
    short: 'Eid al-Fitr',
    greeting: 'Eid Mubarak!',
    subtitle: 'Wishing you and your family a joyful Eid al-Fitr.',
    emoji: '🌙',
    gradient: 'from-teal-700 via-emerald-500 to-amber-300',
    border: 'border-teal-300/50',
    text: 'text-white',
    accent: '#14b8a6',
    confetti: ['#14b8a6', '#10b981', '#facc15', '#ffffff'],
  },
  eidadha: {
    short: 'Eid al-Adha',
    greeting: 'Eid Mubarak!',
    subtitle: 'Warm wishes for a blessed Eid al-Adha.',
    emoji: '🌙',
    gradient: 'from-green-700 via-teal-500 to-emerald-300',
    border: 'border-green-300/50',
    text: 'text-white',
    accent: '#059669',
    confetti: ['#059669', '#14b8a6', '#facc15', '#ffffff'],
  },
  hanukkah: {
    short: 'Hanukkah',
    greeting: 'Happy Hanukkah!',
    subtitle: 'Eight nights of light — and a little extra cheer.',
    emoji: '🕎',
    gradient: 'from-blue-800 via-blue-600 to-sky-400',
    border: 'border-blue-300/50',
    text: 'text-white',
    accent: '#2563eb',
    confetti: ['#2563eb', '#0ea5e9', '#facc15', '#ffffff'],
  },
  cincodemayo: {
    short: 'Cinco de Mayo',
    greeting: 'Happy Cinco de Mayo!',
    subtitle: 'Fiesta time — celebrate with these seasonal deals.',
    emoji: '🎉',
    gradient: 'from-green-600 via-lime-500 to-red-500',
    border: 'border-lime-300/50',
    text: 'text-white',
    accent: '#84cc16',
    confetti: ['#84cc16', '#dc2626', '#facc15', '#ffffff'],
  },
  spring: {
    short: 'Spring',
    greeting: 'Hello, Spring!',
    subtitle: 'Blossoms, longer days and a fresh-season tune-up.',
    emoji: '🌸',
    gradient: 'from-pink-400 via-emerald-300 to-green-500',
    border: 'border-pink-300/50',
    text: 'text-white',
    accent: '#f472b6',
    confetti: ['#f9a8d4', '#86efac', '#fde68a', '#ffffff'],
  },
  summer: {
    short: 'Summer',
    greeting: 'Hello, Summer!',
    subtitle: 'Sunniest rides deserve a summer-ready bike.',
    emoji: '☀️',
    gradient: 'from-amber-400 via-yellow-300 to-sky-400',
    border: 'border-amber-300/50',
    text: 'text-white',
    accent: '#f59e0b',
    confetti: ['#fde68a', '#38bdf8', '#fca5a5', '#ffffff'],
  },
  autumn: {
    short: 'Autumn',
    greeting: 'Hello, Autumn!',
    subtitle: 'Golden leaves — the perfect time for a service.',
    emoji: '🍂',
    gradient: 'from-amber-700 via-orange-500 to-amber-400',
    border: 'border-orange-300/50',
    text: 'text-white',
    accent: '#d97706',
    confetti: ['#d97706', '#b45309', '#f59e0b', '#fde68a'],
  },
  winter: {
    short: 'Winter',
    greeting: 'Hello, Winter!',
    subtitle: 'Cold-weather care for every bike in the shed.',
    emoji: '❄️',
    gradient: 'from-slate-700 via-sky-600 to-blue-300',
    border: 'border-sky-300/50',
    text: 'text-white',
    accent: '#38bdf8',
    confetti: ['#ffffff', '#bae6fd', '#c7d2fe', '#e0e7ff'],
  },
  mayday: {
    short: 'May Day',
    greeting: 'Happy May Day!',
    subtitle: 'Spring is in full swing — ride out and enjoy it.',
    emoji: '🌷',
    gradient: 'from-pink-400 via-emerald-400 to-green-600',
    border: 'border-emerald-300/50',
    text: 'text-white',
    accent: '#34d399',
    confetti: ['#f9a8d4', '#86efac', '#fde68a', '#ffffff'],
  },
  springbank: {
    short: 'Spring Bank Holiday',
    greeting: 'Happy Spring Bank Holiday!',
    subtitle: 'An extra day off — get the bike ready to roll.',
    emoji: '🌿',
    gradient: 'from-emerald-600 via-green-500 to-lime-400',
    border: 'border-green-300/50',
    text: 'text-white',
    accent: '#16a34a',
    confetti: ['#86efac', '#fde68a', '#a3e635', '#ffffff'],
  },
  summerbank: {
    short: 'Summer Bank Holiday',
    greeting: 'Happy Summer Bank Holiday!',
    subtitle: 'Make the most of the long weekend on two wheels.',
    emoji: '🏖️',
    gradient: 'from-sky-500 via-cyan-400 to-amber-300',
    border: 'border-cyan-300/50',
    text: 'text-white',
    accent: '#0ea5e9',
    confetti: ['#38bdf8', '#fde68a', '#fca5a5', '#ffffff'],
  },
  fathersday: {
    short: "Father's Day",
    greeting: "Happy Father's Day!",
    subtitle: 'Gift the dad who rides something he will love.',
    emoji: '👔',
    gradient: 'from-sky-700 via-blue-500 to-cyan-400',
    border: 'border-sky-300/50',
    text: 'text-white',
    accent: '#0ea5e9',
    confetti: ['#38bdf8', '#0ea5e9', '#fde68a', '#ffffff'],
  },
  mothersday: {
    short: "Mother's Day",
    greeting: "Happy Mother's Day!",
    subtitle: 'Treat the mum who loves to ride.',
    emoji: '💐',
    gradient: 'from-rose-400 via-pink-400 to-fuchsia-400',
    border: 'border-pink-300/50',
    text: 'text-white',
    accent: '#f472b6',
    confetti: ['#fb7185', '#f9a8d4', '#fde68a', '#ffffff'],
  },
  pancakes: {
    short: 'Pancake Day',
    greeting: 'Happy Pancake Day!',
    subtitle: 'Flip a stack — then flip a fresh deal.',
    emoji: '🥞',
    gradient: 'from-amber-500 via-yellow-400 to-orange-400',
    border: 'border-amber-300/50',
    text: 'text-white',
    accent: '#f59e0b',
    confetti: ['#fbbf24', '#f59e0b', '#fde68a', '#ffffff'],
  },
  ramadan: {
    short: 'Ramadan',
    greeting: 'Ramadan Mubarak!',
    subtitle: 'Wishing you a peaceful and blessed month.',
    emoji: '🌙',
    gradient: 'from-teal-700 via-emerald-500 to-amber-300',
    border: 'border-teal-300/50',
    text: 'text-white',
    accent: '#14b8a6',
    confetti: ['#14b8a6', '#10b981', '#fde68a', '#ffffff'],
  },
  dussehra: {
    short: 'Dussehra',
    greeting: 'Happy Dussehra!',
    subtitle: 'Celebrating the victory of good over evil.',
    emoji: '🏹',
    gradient: 'from-orange-600 via-amber-500 to-yellow-400',
    border: 'border-orange-300/50',
    text: 'text-white',
    accent: '#f97316',
    confetti: ['#f97316', '#fbbf24', '#fca5a5', '#ffffff'],
  },
  stgeorge: {
    short: "St. George's Day",
    greeting: "Happy St. George's Day!",
    subtitle: 'Celebrate England with a great ride.',
    emoji: '🏴',
    gradient: 'from-red-700 via-red-500 to-slate-200',
    border: 'border-red-300/50',
    text: 'text-white',
    accent: '#dc2626',
    confetti: ['#dc2626', '#ffffff', '#b91c1c', '#e5e7eb'],
  },
  aprilsfools: {
    short: "April Fool's Day",
    greeting: "Happy April Fool's Day!",
    subtitle: 'No pranks here — just genuine good deals.',
    emoji: '🃏',
    gradient: 'from-lime-400 via-sky-400 to-fuchsia-400',
    border: 'border-lime-300/50',
    text: 'text-white',
    accent: '#a3e635',
    confetti: ['#a3e635', '#38bdf8', '#f472b6', '#fbbf24'],
  },
  earthday: {
    short: 'Earth Day',
    greeting: 'Happy Earth Day!',
    subtitle: 'Two wheels, zero emissions — ride green.',
    emoji: '🌍',
    gradient: 'from-green-600 via-emerald-400 to-sky-400',
    border: 'border-green-300/50',
    text: 'text-white',
    accent: '#22c55e',
    confetti: ['#22c55e', '#86efac', '#38bdf8', '#ffffff'],
  },
  backtoschool: {
    short: 'Back to School',
    greeting: 'Back to School!',
    subtitle: 'Get the family bikes road-ready for the school run.',
    emoji: '🎒',
    gradient: 'from-orange-600 via-amber-500 to-yellow-400',
    border: 'border-amber-300/50',
    text: 'text-white',
    accent: '#ea580c',
    confetti: ['#d97706', '#f59e0b', '#fde68a', '#ffffff'],
  },
  bonfirenight: {
    short: 'Bonfire Night',
    greeting: 'Happy Bonfire Night!',
    subtitle: 'Remember, remember — stay bright and be seen.',
    emoji: '🎆',
    gradient: 'from-orange-600 via-red-500 to-indigo-800',
    border: 'border-orange-300/50',
    text: 'text-white',
    accent: '#f97316',
    confetti: ['#f97316', '#fbbf24', '#ef4444', '#ffffff'],
  },
  remembranceday: {
    short: 'Remembrance Day',
    greeting: 'We Will Remember Them',
    subtitle: 'Pausing to honour and remember.',
    emoji: '🌺',
    gradient: 'from-red-800 via-red-600 to-slate-400',
    border: 'border-red-300/50',
    text: 'text-white',
    accent: '#b91c1c',
    confetti: ['#dc2626', '#b91c1c', '#f87171', '#e5e7eb'],
  },
  boxingday: {
    short: 'Boxing Day',
    greeting: 'Happy Boxing Day!',
    subtitle: 'Boxing Day bargains — enjoy the sales.',
    emoji: '🎁',
    gradient: 'from-red-600 via-rose-400 to-sky-300',
    border: 'border-rose-300/50',
    text: 'text-white',
    accent: '#e11d48',
    confetti: ['#e11d48', '#38bdf8', '#ffffff', '#fde68a'],
  },
  januarysales: {
    short: 'January Sales',
    greeting: 'January Sales Are Here!',
    subtitle: 'Start the year with a fresh deal.',
    emoji: '🏷️',
    gradient: 'from-amber-500 via-yellow-400 to-red-500',
    border: 'border-amber-300/50',
    text: 'text-white',
    accent: '#f59e0b',
    confetti: ['#fbbf24', '#facc15', '#ef4444', '#ffffff'],
  },
  blackfriday: {
    short: 'Black Friday',
    greeting: 'Happy Black Friday!',
    subtitle: 'Our biggest deals of the year — grab them fast.',
    emoji: '🛍️',
    gradient: 'from-amber-500 via-yellow-400 to-neutral-900',
    border: 'border-amber-300/50',
    text: 'text-white',
    accent: '#f59e0b',
    confetti: ['#fbbf24', '#facc15', '#111827', '#ffffff'],
  },
  cybermonday: {
    short: 'Cyber Monday',
    greeting: 'Happy Cyber Monday!',
    subtitle: 'Online-only savings on parts, kit and service.',
    emoji: '💻',
    gradient: 'from-cyan-500 via-sky-400 to-blue-800',
    border: 'border-cyan-300/50',
    text: 'text-white',
    accent: '#06b6d4',
    confetti: ['#22d3ee', '#38bdf8', '#67e8f9', '#ffffff'],
  },
  smallbusinesssaturday: {
    short: 'Small Business Saturday',
    greeting: 'Happy Small Business Saturday!',
    subtitle: "Shop local — thanks for backing your local bike shop.",
    emoji: '🏬',
    gradient: 'from-amber-500 via-emerald-400 to-green-700',
    border: 'border-emerald-300/50',
    text: 'text-white',
    accent: '#10b981',
    confetti: ['#fbbf24', '#34d399', '#fde68a', '#ffffff'],
  },
};

/** The banner for a theme, or `null` for `'none'` / unknown inputs. */
export function themeBannerFor(theme: SeasonalThemeId | string | undefined | null): ThemeBanner | null {
  if (!theme || theme === 'none') return null;
  return THEME_BANNERS[theme as HolidayThemeId] ?? null;
}
